# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 962f8df2eef3b1c88387c0b18a3b31dd96b037f94ca0d5ea320f747c1b0f7503cfbebb9c250ae8752d5dc549cbaac4f5e353ad7387ef9df6ca1b9695bfa7c043

test:
  secret_key_base: e77d07bbbf0b343eedd97526a1d3774dd0146397db9a31fa5556b747b0aef12385e58b13cce51f84f1b98f871aa2350c46dc99f0da215e263ea8e5a4a79ed7fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
